[unification] Move //zircon/system/ulib/ramdevice-client to the GN build
Affected libraries:
//zircon/system/ulib/ramdevice-client

scripts/unification/verify_element_move.py --reference local/initial.json:

Error     aux         element removed: lib/profile/libramdevice-client.so
Error     aux         element removed: lib/asan-ubsan/libramdevice-client.so
Error     aux         element removed: lib/ubsan-sancov-full/libramdevice-client.so
Error     aux         element removed: lib/ubsan-sancov/libramdevice-client.so
Error     aux         element removed: lib/sancov/libramdevice-client.so
Error     aux         element removed: lib/ubsan/libramdevice-client.so
Error     aux         element removed: lib/asan/libramdevice-client.so
Error     aux         size change for lib/libramdevice-client.so: -74% (85.5K)
Warning   aux         size change for test/ddk/fshost-test-test: -4% (432.0K)
Error     aux         shared library removed from test/fs/blobfs-large-integration-fragmentation-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/fs-test-utils-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/blobfs-large-integration-use-second-bitmap-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/fs-bench-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/minfs-unit-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/minfs-micro-benchmark-test: libdriver-integration-test.so
Error     aux         shared library removed from test/sys/fs-recovery-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/blobfs-unit-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/blobfs-large-integration-short-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/minfs-power-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/minfs-integration-test: libdriver-integration-test.so
Error     aux         shared library removed from test/sys/ram-nand-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/blobfs-large-integration-no-space-test: libdriver-integration-test.so
Error     aux         shared library removed from test/sys/sysconfig-sync-client-test: libdriver-integration-test.so
Error     aux         shared library removed from test/sys/fs-test-support-test: libdriver-integration-test.so
Error     aux         shared library removed from test/ddk/block-watcher-test-test: libdriver-integration-test.so
Error     aux         shared library removed from lib/libramdevice-client.so: libtrace-engine.so
Error     aux         shared library removed from lib/libramdevice-client.so: libasync-default.so
Error     aux         shared library removed from test/fs/fs-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/blobfs-integration-test: libdriver-integration-test.so
Error     aux         shared library removed from test/sys/biotime-test: libdriver-integration-test.so
Error     aux         shared library removed from test/sys/disk-inspector-unit-test: libdriver-integration-test.so
Error     aux         shared library removed from test/fs/fs-management-test: libdriver-integration-test.so
Error     aux         shared library removed from test/ddk/fshost-test-test: libdriver-integration-test.so
Error     image       size change for lib/libramdevice-client.so: -74% (85.5K)
Error     image       shared library removed from bin/iotime: libdriver-integration-test.so
Error     image       shared library removed from bin/install-disk-image: libdriver-integration-test.so
Error     image       shared library removed from bin/fvm-check: libdriver-integration-test.so
Error     image       shared library removed from lib/libramdevice-client.so: libtrace-engine.so
Error     image       shared library removed from lib/libramdevice-client.so: libasync-default.so
Error     image       shared library removed from bin/nand-loader: libdriver-integration-test.so
Error     image       shared library removed from bin/miscsvc: libdriver-integration-test.so
Error     image       shared library removed from bin/fshost: libdriver-integration-test.so
Warning   tests       size change for test/ddk/fshost-test-test: -4% (432.0K)
Error     tests       size change for lib/libramdevice-client.so: -74% (85.5K)
Error     tests       shared library removed from test/fs/blobfs-large-integration-fragmentation-test: libdriver-integration-test.so
Error     tests       shared library removed from test/ddk/fshost-test-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/minfs-unit-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/minfs-integration-test: libdriver-integration-test.so
Error     tests       shared library removed from test/sys/fs-recovery-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/blobfs-large-integration-short-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/blobfs-large-integration-no-space-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/minfs-power-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/blobfs-large-integration-use-second-bitmap-test: libdriver-integration-test.so
Error     tests       shared library removed from test/sys/ram-nand-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/fs-test-utils-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/minfs-micro-benchmark-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/fs-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/blobfs-unit-test: libdriver-integration-test.so
Error     tests       shared library removed from test/sys/fs-test-support-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/blobfs-integration-test: libdriver-integration-test.so
Error     tests       shared library removed from lib/libramdevice-client.so: libtrace-engine.so
Error     tests       shared library removed from lib/libramdevice-client.so: libasync-default.so
Error     tests       shared library removed from test/sys/sysconfig-sync-client-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/fs-bench-test: libdriver-integration-test.so
Error     tests       shared library removed from test/sys/biotime-test: libdriver-integration-test.so
Error     tests       shared library removed from test/sys/disk-inspector-unit-test: libdriver-integration-test.so
Error     tests       shared library removed from test/fs/fs-management-test: libdriver-integration-test.so
Error     tests       shared library removed from test/ddk/block-watcher-test-test: libdriver-integration-test.so
Error     zbi_tests   removed from bootsvc-integration-tests bootfs: lib/libdriver-integration-test.so
Error: summaries do not match!

Generated with //scripts/unification/move_cpp_library.py

Bug: 36548
Change-Id: I0d7fb86b59dec2bc357e9c7788e5044c5f40625b
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/380563
Commit-Queue: Theodore Dubois <tbodt@google.com>
Reviewed-by: P.Y. Laligand <pylaligand@google.com>
Testability-Review: Shai Barack <shayba@google.com>